#!/bin/sh

 alias \
     cp="cp -r -iv" \
	 mv="mv -iv" \
	 rm="rm -r -iv" \
	 mkd="mkdir -pv" \
	 ls="ls --color" \
	 lls="lsd -l --color --icon never" \
	 la="lsd -a --color --icon never" \
	 lla="lsd -la --color --icon never" \
	 lh="lsd -d .* --color --icon never" \
	 llh="lsd -ld .* --color --icon never" \
	 grep="grep --color=auto" \
	 diff="diff --color=auto" \
 	 ccat="highlight --out-format=ansi" \
	 magit="nvim -c MagitOnly" \
	 v="$EDITOR" \
     vim="$EDITOR" \
	 ytdl="youtube-dl --add-metadata -i" \
	 yta="yt -x -f bestaudio/best" \
	 ytv="sh ~/.config/scripts/youtube-viewer.sh" \
	 ffmpeg="ffmpeg -hide_banner" \
	 mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	 ka="killall" \
	 g="git" \
	 gc="git clone" \
	 ga="git add" \
	 gr="git restore --staged" \
	 gcm="git commit -m" \
 	 gcnm="git commit -a --allow-empty-message -m ''" \
   	 gs="git status" \
	 gp="git push" \
     sudo="doas" \
	 magit="nvim -c MagitOnly" \
	 mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	 passwdgen="sh /$HOME/.config/scripts/passwdgen.sh" \
     size="du -h --max-depth=1"
