#!/bin/sh

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

 alias \
         cp="cp -r -iv" \
	 mv="mv -iv" \
	 rm="rm -r -iv" \
	 mkd="mkdir -pv" \
	 ls="ls --color" \
	 lls="ls -l --color" \
	 la="ls -a --color" \
	 lla="ls -la --color" \
	 lh="ls -d .* --color" \
	 llh="ls -ld .* --color" \
	 grep="grep --color=auto" \
	 diff="diff --color=auto" \
 	 ccat="highlight --out-format=ansi" \
	 magit="nvim -c MagitOnly" \
	 f="$FILE" \
	 e="$EDITOR" \
	 v="$EDITOR" \
	 yt="youtube-dl --add-metadata -i" \
	 yta="yt -x -f bestaudio/best" \
	 YT="youtube-viewer" \
	 ffmpeg="ffmpeg -hide_banner" \
	 mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	 ka="killall" \
	 g="git" \
	 gc="git clone" \
	 ga="git add" \
	 gr="git restore --staged" \
	 gcm="git commit -m" \
 	 gcnm="git commit -a --allow-empty-message -m ''" \
	 gs="git status" \
	 gp="git push" \
	 sudo="doas" \
	 magit="nvim -c MagitOnly" \
	 mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	 passwdgen="sh /$HOME/.config/scripts/passwdgen.sh"
