#!/bin/bash

# infinite history
HISTSIZE= HISTFILESIZE= 

# disable ctrl-s and ctrl-q
stty -ixon

# cd into any dir by typing just the dir name 
shopt -s autocd

# ccache
export PATH="/usr/lib/ccache/bin${PATH:+:}$PATH"
export CCACHE_DIR="/var/cache/ccache"

# load aliases
[ -f "/root/.aliasrc" ] && source "/root/.aliasrc"

# load bash completion
[ -r /usr/share/bash-completion/bash_completion   ] && . /usr/share/bash-completion/bash_completion

# editor
set -o vi
export EDITOR='vi'
export VISUAL='vi'

# prompt
export PS1="\[$(tput bold)\]\[$(tput setaf 5)\]\h\[$(tput setaf 2)\]:\[$(tput setaf 4)\][\[$(tput setaf 1)\]\u\[$(tput setaf 4)\]]\[$(tput setaf 2)\]: \[\e[36m\]\W\[\e[m\] \[$(tput bold)\]\[$(tput setaf 3)\]\\$ \[$(tput sgr0)\]"
